../../../pyodbc.pyi,sha256=cLuLanSS0Vry9aUUvn-i1lpDxHiDcMQwQFypGWqD__E,13127
pyodbc-4.0.34.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
pyodbc-4.0.34.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.34.dist-info/METADATA,sha256=9OvmhDABSFHthoXvVk6wdB2IT48YRKR76m_UntEfUBE,2719
pyodbc-4.0.34.dist-info/RECORD,,
pyodbc-4.0.34.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyodbc-4.0.34.dist-info/WHEEL,sha256=zKWk4ojSD57YSE4Qs9Y_1WZeqKAYwG2-9Qy4o4_ajdo,114
pyodbc-4.0.34.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc.cpython-310-x86_64-linux-gnu.so,sha256=TRF0gEHW6S32MdzB24rwZq3dyENCPJ8LG0rpxYoymJg,779968
pyodbc.libs/libltdl-738907ff.so.7,sha256=TaG295L91l1AQ1GgX8V3tRaHE9eN6Pe96nJoyztuSAo,43288
pyodbc.libs/libodbc-2003e41d.so.2.0.0,sha256=E3p9jC0jRPTH3s523yhOwnkhtT0yoefH-bXKClJcwyA,449832
